### ISSUE TITLE
Should disable the hotkey if you typing in text-chat and hit K...the emote menu comes up :(

### ISSUE THREAD

**Issue by Aledark789** [niciel/VSMods#1]
Should disable the hotkey if you typing in text-chat and hit K...the emote menu comes up :(

**Comment by niciel** [comment]
right now im waiting for response, or for fix survival mode if its a bug, https://github.com/anegostudios/VintageStory-Issues/issues/1543

**Comment by niciel** [comment]
Fixed, Little bit tricky but works
